name: dynamic_gaussians
channels:
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cuda-toolkit
  - pip
  - pip:
    - pillow
    - open3d
    - pydub
    - numpy==1.26.4
    - scipy
    - tqdm
    - pycairo
    - PyGObject
    - pybind11